pipeline {
    agent any

    stages {
        stage("Clone") {
            steps {
                sh "echo 'Cloning from GitHub...'"
                git branch: "main", url: 'https://github.com/pipecm/kibernum-quiz-app.git'
                sh "echo 'Cloned successfully'"
            }
        }

        stage("Build") {
            steps {
                sh "echo 'Building app...'"
                sh "mvn clean package"
                sh "echo 'Built successfully'"
            }
        }

        stage("Test") {
            steps {
                sh "echo 'Running tests...'"
                sh "mvn test"
                sh "echo 'Tests ran successfully'"
            }
        }

        stage("Build Docker image") {
            steps {
                sh "echo 'Deploying...'"
                sh "docker build . -t quiz-app -f docker/Dockerfile"
                sh "echo 'Deployment finished successfully...'"
            }
        }

         stage("Run with Terraform") {
            steps {
                sh "echo 'Applying Terraform'"
                sh "terraform -chdir='./terraform' init"
                sh "terraform -chdir='./terraform' apply --auto-approve"
                sh "echo 'Applied Terraform successfully'"
            }
         }
    }
}